### ISSUE TITLE
problem in linux

### ISSUE THREAD

**Issue by sari777** [unclevito2017/VBCr-Automation#1]
how to run in linux.? a plenty of errors regarding microsoft dll libraries are coming.
how to overcome this.?
and you said there is no need to download VBCr.exe file from the wondering philospher. but it wants.

**Comment by unclevito2017** [comment]
I think you misunderstood THE README. this refer to the fact the program automatically increments the vbcr.exe program SO YOU DON'T HAVE TO. My program is in python which  controls VBCr.exe which is a windows program.  VBCr.exe only runs on windows and you need it to work with . Maybe wondering philospher can write a linux version but without it the program will not work and he did not supply the source code so he is the only person who can make it in linux. If you want bitcrack random in linux I can make that with the same control functions but that is not a prefix finder

**Comment by sari777** [comment]
right thanks for answer.
